[build]
  base = "server"
  publish = "public"

[functions]
  directory = "."

[functions.server]
  external_node_modules = ["mongoose", "cloudinary"]
  node_bundler = "esbuild"
  format = "esm"

[[redirects]]
  from = "/api/*"
  status = 200
  force = true
  to = "/.netlify/functions/server/:splat"
