[build]
  # Directs Netlify to process dependencies inside the server directory
  base = "server"
  publish = "public"

[functions]
  node_bundle = true
  # Tells Netlify where your backend function files are located
  directory = "."

[functions.server]
  external_node_modules = ["mongoose"]
  js_config = { node_bundler = "esbuild", format = "esm" }

# Maps your frontend calls directly into the serverless backend function
[[redirects]]
  from = "/api/*"
  status = 200
  force = true
  to = "/.netlify/functions/server/:splat"
